import { readFile } from 'node:fs/promises';
// Only the frame generated by our browser test is sent; no user recordings.
const image = await readFile('test-results/app-記録中に映像をオン・オフでき、オフでは添付を止め、単発読取りと記録を保存する/synthetic-frame.jpg');
const response = await fetch('http://127.0.0.1:5173/api/observe-frame', { method: 'POST', headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ image: image.toString('base64'), mimeType: 'image/jpeg' }), signal: AbortSignal.timeout(65000) });
const result = await response.json();
if (!response.ok || !result.text?.trim()) { console.error('Vision API check failed: ' + (result.error || 'empty response')); process.exitCode = 1; }
else console.log('Vision API: OK\n' + result.text);
